- hosts: localhost
  tasks:
    - name: Install git
      yum: name=git state=latest 
      become: yes
      become_method: sudo

    - name: Clone repo MeirDukhan / devops
      git: clone=yes repo=https://github.com/MeirDukhan/devops.git dest=/home/ec2-user/DevOps_Ex1 update=no

    - name: Clone repo MeirDukhan / devops
      git: clone=yes repo=https://github.com/MeirDukhan/spring-petclinic.git dest=/home/ec2-user/SP update=no
    
    - name: Install docker and add 'docker' groupto "ec2-user"
      yum: name=docker state=latest
      become: yes
      become_method: sudo

    - name: Add 'docker' group to "ec2-user"
      become: yes
      become_method: sudo
      user: name=ec2-user groups=docker append=yes

    - name: STart the docker service
      become: yes
      become_method: sudo
      service: name=docker state=started

    - name: Untar Maven 
      # become: yes
      # become_method: sudo
      unarchive:
          src: http://apache.spd.co.il/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
          copy: no
          creates: /home/ec2-user/DevOps_Ex2/apache-maven-3.3.9
          dest: /home/ec2-user/DevOps_Ex2

